version: "3"
services:
  servers_distribute:
      ports:
         - 8080:8080
      build:
        context: ./servers_distribute
        dockerfile: ./servers_distribute.dockerfile
      restart: always
      deploy:
        mode: replicated
        replicas: 1
  mongo:
      image: mongo
      ports: 
        - 27017:27017
      restart: always
      environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: users
      deploy:
         mode: replicated
         replicas: 1  
  users:
      ports:
         - 8080:8081
      build:
         context: ./user_mode
         dockerfile: ./user_mode.dockerfile   
      volumes:
        - ./db-data/mongo:/data/db
      deploy:
         mode: replicated
         replicas: 1 
