version: "3"
services:
  servers_distribute:
      ports:
         - 8080:8080
      build:
        context: ./servers_distribute
        dockerfile: ./servers_distribute.dockerfile
      restart: always
      deploy:
        mode: replicated
        replicas: 1
  user_db:
      ports:
        - 3306:3306
      image: mysql:latest 
      volumes: 
        - ./db-data/.:/docker-entrypoint-initdb.d
      restart: always
      deploy: 
         mode: replicated
         replicas: 1
  users:
      ports:
         - 8081:8081
      build:
         context: ./user_mode
         dockerfile: ./user_mode.dockerfile   
      volumes:
        - ./db-data/mongo:/data/db
      deploy:
         mode: replicated
         replicas: 1 
